# Generated by Django 5.0.1 on 2024-01-08 11:31

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("temperature", models.FloatField()),
                ("feels_like", models.FloatField()),
                ("weather_description", models.CharField(max_length=255)),
                ("clouds", models.IntegerField()),
                ("time", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
