# Generated by Django 5.0.1 on 2024-01-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weather",
            name="clouds",
            field=models.CharField(max_length=4),
        ),
    ]
